# Generated by Django 5.0.7 on 2024-08-27 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='count',
            new_name='countval',
        ),
    ]
