# Generated by Django 5.0.7 on 2024-08-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0002_rename_count_cartmodel_countval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='productID',
            new_name='productcart',
        ),
        migrations.RenameField(
            model_name='cartmodel',
            old_name='userID',
            new_name='usercart',
        ),
    ]
