# Generated by Django 5.0.7 on 2024-08-29 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0003_rename_productid_cartmodel_productcart_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('orderstatus', models.CharField(choices=[('P', 'pending'), ('S', 'shipped'), ('D', 'delivered'), ('C', 'cancelled')], default='P', max_length=1)),
                ('orderproduct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nova.productdata')),
                ('orderuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('0', 'Noratings'), ('1', '1 rating'), ('2', '2 ratings'), ('3', '3 ratings'), ('4', '4 ratings'), ('5', '5 ratings')], default='0', max_length=1)),
                ('review', models.TextField(null=True)),
                ('reviewproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nova.productdata')),
                ('reviewuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
