# Generated by Django 5.0.7 on 2024-08-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0004_ordersmodel_reviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodel',
            name='ordercount',
            field=models.IntegerField(default=1),
        ),
    ]
