# Generated by Django 5.0.7 on 2024-08-29 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0005_ordersmodel_ordercount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='trending',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserdataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilestatus', models.BooleanField(default=False)),
                ('contact', models.IntegerField(max_length=10, null=True)),
                ('address', models.TextField(null=True)),
                ('datauser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
