# Generated by Django 5.0.7 on 2024-08-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0006_productdata_trending_userdatamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatamodel',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
