# Generated by Django 5.0.7 on 2024-08-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0007_alter_userdatamodel_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdatamodel',
            old_name='address',
            new_name='city',
        ),
        migrations.AddField(
            model_name='userdatamodel',
            name='district',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userdatamodel',
            name='lmark',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userdatamodel',
            name='local',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userdatamodel',
            name='pincode',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userdatamodel',
            name='state',
            field=models.TextField(null=True),
        ),
    ]
