# Generated by Django 5.0.7 on 2024-08-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0008_rename_address_userdatamodel_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='reviewproduct',
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='rating',
            field=models.CharField(choices=[('0', 'No ratings'), ('1', '1 rating'), ('2', '2 ratings'), ('3', '3 ratings'), ('4', '4 ratings'), ('5', '5 ratings')], default='0', max_length=1),
        ),
    ]
