# Generated by Django 5.0.7 on 2024-08-29 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0010_productdata_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdata',
            name='reviews',
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='reviewproduct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nova.productdata'),
        ),
    ]
